perl-net-saml2/perl-Net-SAML2

lib/Net/SAML2/Protocol/AuthnRequest.pm
=> Fix perl 5.10 issue with `//=` syntax

lib/Net/SAML2/SP.pm, t/02-create-sp.t
We can now always use these attributes without if defined checks
Signed-off-by: Wesley Schwengle <wesleys@opperschaap.net>
=> Add defaults to authnreq_signed and want_assertions_signed

lib/Net/SAML2/SP.pm
The builder is lazy, so will only be called when needed. Additionally, you
cannot inject it at object initialization.
Signed-off-by: Wesley Schwengle <wesleys@opperschaap.net>
=> Use builder for _cert_text

lib/Net/SAML2/SP.pm, t/02-create-sp.t
The constructor now allows you to disable signing the metadata by supplying
`sign_metadata => 0`.
Additionally the plain metadata generation is now done via `generate_metadata`.
This allows for subclasses to override the metadata generation. Eg, we can add
requested attributes or tweak things before we sign the metadata.
Signed-off-by: Wesley Schwengle <wesleys@opperschaap.net>
=> Make signing metadata optional

lib/Net/SAML2/SP.pm, t/02-create-sp.t
Not all URI's are mandatory for metadata creation
* slo_url_post
* slo_url_soap
These can now be omitted in the constructor and we are able to build the
correct metadata.
=> Make some URI's optional in the constructor

Dockerfile, dist.ini
The dist.ini has AutoPreqs enabled, so most of them, if not all should be found
automaticly. Only those who require special treatement, eg, need to have a
minimum version must stay.
=> Remove dependencies from dist.ini

.github/workflows/linux.yml
=> Run Github actions on pull requests

.github/workflows/linux.yml, t/02-create-sp.t, t/lib/Test/Net/SAML2/Util.pm
Setup a bare minimum SP with just the defaults so it is easier to override
these defaults. Currently, in order to test this minimal thing we need to setup
the minimal thing while we can easily expand the caller to add their flavor.
=> Only use defaults/required attrs in net_saml2_sp() test method

lib/Net/SAML2/IdP.pm, t/01-create-idp.t
The SAML spec says:
<NameIDFormat> [Zero or More]
Zero or more elements of type anyURI that enumerate the name identifier formats supported by
this system entity acting in this role. See Section 8.3 of [SAMLCore] for some possible values for
this element.
In the function format we claim that when nothing is set, you get undef. The
current code always sends a name-id-format to the caller even if the metadata
did not provide any data.
=> Remove setting default format when not present in metadata

.mailmap, dist.ini
We can automaticly add contributors via the cvs system. Duplicates are removed
via a .mailmap entry
=> Fix contributers automaticly from git

lib/Net/SAML2/SP.pm, t/02-create-sp.t
This way you can later ask the SP which one it is with the
`get_default_assertion_service` call. This is handy for those who configure the
SP and later on need to know the index of the assertion consumer service. Some
IdP's require this in the AuthnRequest and this way you can easily query the
SP.
=> Add the index in the assertion_consumer_service

dist.ini, lib/Net/SAML2.pm
By setting the version in lib/Net/SAML2.pm downstream developers can use a git
repo to install Net::SAML2 and still keep their dependencies correct. If a
module requires Net::SAML2 v0.56 and the version in git is not set, it cannot
validate the module version and it breaks the versioning check of for example
cpanminus. By setting the version in the main module we allow downstream users
to test/play with development versions of Net::SAML2.
=> Set version in main module for downstream developers

lib/Net/SAML2/Protocol/ArtifactResolve.pm, t/10-artifact-resolve.t
The previous incarnation supplied a default when as_xml was called. Not all
code requires a provider, so we don't use it if nothing has been provided by
the caller.
=> Really make provider optional in Protocol::ArtifactResolve

.github/workflows/linux.yml, lib/Net/SAML2/Binding/SOAP.pm
This way one can extend/override the builder for the UA object and makes it
easier to extend the Binding.
=> Add builder to Binding::SOAP for LWP::UA

.github/workflows/linux.yml, LICENSE, dist.ini
Some deps are more likely to break w/ gh actions. It is rather annoying because
it stops the build of all the testsuites from 5.10-5.3x.
Maybe we should split supported perl and unsupported perls?
=> Install deps manually

.github/workflows/linux.yml
I want to get rid of the false negatives with the PR submissions because the
deps fail to install. cpm also seems to be a bit quicker than cpanminus.
=> Use cpm instead of cpanminus

lib/Net/SAML2/SP.pm, xt/testapp/lib/Saml2Test.pm
Some testing revealed that the nameid_format cannot be passed as an empty string.  Probably a better way to do this but if this is fine I will merge and release a trial
=> nameid_format cannot be a zero length string

lib/Net/SAML2/Binding/Redirect.pm, t/06-redirect-binding.t
=> Make params optional in Binding::Redirect for SAMLResponse

lib/Net/SAML2/Protocol/LogoutRequest.pm, lib/Net/SAML2/SP.pm, t/07-logout-request.t
The Format attribute in NameID will only be set if there is a nameid format
configured. The NameQualifier and SPNameQualifier are only set when this is
configured by setting `include_name_qualifier`. This is because the SAML spec
says:
> The NameQualifier and SPNameQualifier attributes SHOULD be omitted unless the
> element or format explicitly defines their use and semantics.
The SAML spec also says that if the NameID Format is
`urn:oasis:names:tc:SAML:2.0:nameidformat:persistent` tese two options must be
set. We support this. If there is an affiliation_group_id than we use that
instead of the destination ID because of the same spec.
> In any case, the <saml:NameID> content in the request and its associated
> SPProvidedID attribute MUST contain the most recent name identifier
> …
=> Make attributes in NameID optional

lib/Net/SAML2/Protocol/Assertion.pm
=> Add missing POD for nameid, nameid_format in Protocol::Assertion

.perlcriticrc, lib/Net/SAML2/Binding/Redirect.pm, lib/Net/SAML2/Protocol/ArtifactResolve.pm, lib/Net/SAML2/Protocol/LogoutRequest.pm, lib/Net/SAML2/Types.pm
Add a perlcriticrc file which treats `use Moose` as `use strict; use warnings`.
Add trusted POD for BUILD methods of Moose. These do not need to be documented
as they are part of the Moose API:
https://metacpan.org/dist/Moose/view/lib/Moose/Manual/Construction.pod#BUILD
=> Fix author tests with dzil

t/17-lowercase-url-escaping.t
Add a test for lowercase binding URL escaping.  Couple of small PBP and pod coverage fix.
The test could likely be improved and I generated the URL with a few changes to the Net:SAML2::Binding::Redirect->sign.  It seems to work to demonstrate the issue that the force_lowercase is addressing
=> New test and fix some best practice errors

lib/Net/SAML2/Binding/POST.pm, lib/Net/SAML2/Binding/SOAP.pm, lib/Net/SAML2/Role/VerifyXML.pm, lib/Net/SAML2/SP.pm, lib/Net/SAML2/Util.pm, lib/Net/SAML2/XML/Util.pm, t/04-response.t, t/05-soap-binding.t
The 48e37f57f73ed262c70fd3e843680644332c36c0 changeset implements a couple of breaking changes in regards to how handle_response of Net::SAML2::Binding::SOAP and Net::SAML2::Binding::POST works. We now return the XML of the request so callers can do something with the response. In previous versions this code returned an array of the certificate subject and the XML. However, depending on the how, the subject was a scalar 1 or the DN of the signing certificate. This was confusing to me. I looked into some SAML documentation to figure out why this was done previously.
SAML uses a concept called trust anchors where you can say "I trust this party because of $reasons". These trust anchors can be the issuing party, the DN of the certificate, etc. The previous code implemented a partial solution …
=> BREAKING CHANGES: Verifying XML and trust anchors on SAML responses

lib/Net/SAML2/Binding/Redirect.pm, t/20-path-only-redirect.t, xt/testapp/lighttpd.conf
Fixes #107 
Fixes #108 
Fixes #109
=> Allow URIs that do not include scheme and host in redirect

TUTORIAL.md
Clean up some indents and sync with the wiki page
=> Sync changes with the wiki page and clean up indents

lib/Net/SAML2/SP.pm, t/02-create-sp.t
This prevents a warnings and adds a sane default
=> Add isDefault when isDefault is missing in assertion_consumer_service

Makefile.PL, README, lib/Net/SAML2.pm, lib/Net/SAML2/IdP.pm, t/01-create-idp.t, t/data/idp-metadata-multiple-invalid-use.xml, t/data/idp-metadata-signing-encryption.xml
The problem is that the typing is defined as a hashref of arrays, eg
{
signing => [ pem, pem, pem],
}
and the input was:
[ { signing => [ pem, pem, pem ] } ]
This fails and breaks the IdP code.
Fixes: #116
=> Fix bug where two keys with different usage fails

lib/Net/SAML2/Binding/Redirect.pm, t/06-redirect-binding.t
since, as the documentation already says, some IdP don't check the request signature, we can make it optional
=> make Redirect::key optional

CONTRIBUTORS, LICENSE, Makefile.PL, README, dist.ini, lib/Net/SAML2.pm
Use ContributesFile to tell who is a contributor and update the authors of this module to the previous and current maintainer(s).
=> Set authors and contributors

xt/testapp/config.yml, xt/testapp/environments/development.yml
Many IDPs error with IsPassive set
Dancer treats any warnings as fatal which causes IdPs with multiple certs to die
=> Set sane default values for testing testapp

.github/workflows/linux.yml
t/lexical.t fails every now and than, for more information: https://rt.cpan.org/Public/Bug/Display.html?id=125159
=> Install Sub::Name without running tests

lib/Net/SAML2/Role/ProtocolMessage.pm, lib/Net/SAML2/Types.pm, t/22-types.t
=> Add XsdID as a type for id attribute type checking

xt/testapp/config.yml, xt/testapp/lib/Saml2Test.pm
Some IdPs require ate ACS URL to be specified in the AuthnRequest in some situations.
Indexes not supported in metadata for SingleLogout URLs
=> testapp: miscellaneous changes 

lib/Net/SAML2/Binding/POST.pm, lib/Net/SAML2/Binding/Redirect.pm, lib/Net/SAML2/Binding/SOAP.pm, lib/Net/SAML2/IdP.pm, lib/Net/SAML2/Protocol/Artifact.pm, lib/Net/SAML2/Protocol/ArtifactResolve.pm, lib/Net/SAML2/Protocol/Assertion.pm, lib/Net/SAML2/SP.pm, lib/Net/SAML2/XML/Util.pm
Before, the command `perldoc Net::SAML2::Protocol::Assertion` would produce the output "Net::SAML2::Protocol::Assertion - Net::SAML2::Protocol::Assertion - SAML2 assertion object". The output has been simplified to "Net::SAML2::Protocol::Assertion - SAML2 assertion object".
=> Fix NAME segment of POD for modules.

lib/Net/SAML2/SP.pm, t/02-create-sp.t
http://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf 2.2.3 Complex Type IndexedEndpointType
isDefault [Optional]
An optional boolean attribute used to designate the default endpoint among an indexed set. If omitted, the value is assumed to be false.
In any such sequence of like endpoints based on this type, the default endpoint is the first such endpoint with the isDefault attribute set to true. If no such endpoints exist, the default endpoint is the first such endpoint without the isDefault attribute set to false. If no such endpoints exist, the default endpoint is the first element in the sequence
=> Always return a default assertion service

.github/workflows/perl-eol.yml, .github/workflows/perl-legacy.yml, .github/workflows/perl.yml, .github/workflows/shared-workflow.yml, Makefile.PL, cpanfile, dist.ini
We supported perl 5.12 - perl 5.38, which are about 14 versions of Perl. The CI ran tests for all of them and if one of them failed, they all failed. This is a weebit anoying. Now we split the CI in three sections:
1. We test the last 3 versions of perl
2. We test every version which does not require Debian buster
3. We test every version which requires Debian buster
This allows us to first test the latest versions of Perl and will later fail if older versions fail.
Additionally, bump Perl version to 5.14 as IO::Socket::IP bumped its version requirement as well[^1][^2].
[^1]: https://rt.cpan.org/Public/Bug/Display.html?id=149138
[^2]: https://metacpan.org/dist/IO-Socket-IP/changes
=> Split Github Actions workflow

lib/Net/SAML2.pm, lib/Net/SAML2/AttributeConsumingService.pm, lib/Net/SAML2/RequestedAttribute.pm, lib/Net/SAML2/SP.pm, t/02-create-sp.t, t/27-requested-attribute.t, t/28-attribute-consuming-service.t, t/lib/Test/Net/SAML2/Util.pm
=> Implement Attribute Consuming Service with requested attributes for SP metadata creation

lib/Net/SAML2/SP.pm, t/02-create-sp.t
In the XSD of SAML metadata the signature should be present directly after the md:EntityDescriptor tag as a child node. We placed it at the bottom of the field violating the XSD of SAML metadata.
We should potentially fix it in XML::Sig but that is for another day.
=> Fix signature location bug

lib/Net/SAML2/Protocol/AuthnRequest.pm, lib/Net/SAML2/SP.pm, lib/Net/SAML2/Util.pm, t/lib/Test/Net/SAML2/Util.pm
We've had generate_sp_desciptor_id to override the ID, but this could
very well become a parameter for the constructor. The current ID
attribute was actually used as the issuer. Rename ID to issuer and and
reintroduce ID. We add some deprecation warnings to users so they are
aware of the change.
=> Rename id to issuer for Net::SAML2::SP

lib/Net/SAML2/SP.pm, t/02-create-sp.t
=> Don't mention key usage unless we have both signing and encryption

t/21-artifact-response.t
We used to use the internals of how blessed objects work, by doing `$obj->{foo}` instead of `$obj->foo`. This poses several issues:
1. We can't easily refactor code, because we can rename the attributes but when accessing them in tests it fails.
2. If Moose for $reasons decide to change their API we are also doing things wrong.
So fix it :)
=> Use method, not Moose interals in tests

lib/Net/SAML2/Binding/SOAP.pm, lib/Net/SAML2/Protocol/Artifact.pm, lib/Net/SAML2/Protocol/LogoutRequest.pm, lib/Net/SAML2/Protocol/LogoutResponse.pm, lib/Net/SAML2/Role/ProtocolMessage.pm, t/21-artifact-response.t
This attribute is needed in more than one type, so let's implement it.
Consumers may need to add the required bit.
In addition also add the success() method (although I think we need to
call it is_success).
=> Add in_response_to to Role::ProtocolMessage

lib/Net/SAML2/Binding/POST.pm, lib/Net/SAML2/IdP.pm, lib/Net/SAML2/Protocol/Artifact.pm, lib/Net/SAML2/Protocol/ArtifactResolve.pm, lib/Net/SAML2/Protocol/Assertion.pm, lib/Net/SAML2/Protocol/AuthnRequest.pm, lib/Net/SAML2/Protocol/LogoutResponse.pm, lib/Net/SAML2/Role/ProtocolMessage.pm, lib/Net/SAML2/XML/Util.pm
They are duplicated because we use ABSTRACT from dzil
=> Remove NAME sections in modules

README, dist.ini, lib/Net/SAML2/Binding/SOAP.pm, lib/Net/SAML2/Object/Response.pm, lib/Net/SAML2/Protocol/Artifact.pm, lib/Net/SAML2/Protocol/LogoutRequest.pm, lib/Net/SAML2/Protocol/LogoutResponse.pm, lib/Net/SAML2/Role/ProtocolMessage.pm, t/05-soap-binding.t, t/08-logout-response.t, t/21-artifact-response.t, t/29-response.t, t/data/digid-anul-artifact-response.xml, t/data/response-no-assertion.xml
This is to accomodate responses which do not include Assertions
=>     Add Object::Response to Net::SAML2

dist.ini, lib/Net/SAML2/Protocol/LogoutRequest.pm, t/07-logout-request.t
In 6c63ed1 we introduced some logic to make NameID attributes optional. On the checks is that urn:oasis:names:tc:SAML:2.0:nameidformat:persistent is special. There are two problems with this, one:
urn:oasis:names:tc:SAML:2.0:nameidformat:persistent should be urn:oasis:names:tc:SAML:2.0:nameid-format:persistent. And two: the test in t/07-logout-request.t should test that SPNameQualifier and NameQualifier are actually set and they are now not set (for the test that is). By fixing the typo, we need to change the tests to test the correct thing.
Closes: #213
=> Correctly test NameID attributes

lib/Net/SAML2/Protocol/LogoutResponse.pm, lib/Net/SAML2/SP.pm, t/author/01-confirm-schema.t
Unless required this will go in the next release
=> More updates

lib/Net/SAML2/AttributeConsumingService.pm, lib/Net/SAML2/RequestedAttribute.pm, t/02-create-sp.t
Some IdPs (KPN) don't understand "1" and "0" as boolean values, but insist that the standard says only "true" or "false" are allowed.
A previous commit (bcfc4d249e332628ccab913e12c7b472201ee85f) already fixed several occurences, but it turned out there are more booleans hiding in the metadata XML.
=> Use "true" and "false" for more boolean values

lib/Net/SAML2/Binding/POST.pm
Fixes #229 I was using cert_text in 0.74
=> Revert #123 Useless cert_text

lib/Net/SAML2/SP.pm, t/02-create-sp.t
In 3c87e51 we defined the signing key to be for signing and encryption. This new flag allows consumers to keep old behaviour where the key was/is only used for signing and not encrypting.
=> Set key to be only for signing by adding signing_only in the SP

LICENSE, Makefile.PL, README, cpanfile, dist.ini
0.65 returns an error which does not exist in 0.66. Which seem to be related to Crypt::OpenSSL::RSA disabling use_pkcs1_padding.
=> Bump the requirement for XML::Sig to 0.66
