perl-net-saml2/perl-Net-SAML2

lib/Net/SAML2/Protocol/LogoutRequest.pm
tried using this module but was met with a 'perhaps you forgot to load' error for this package.
could you please merge/release this soon? thanks
=> add missing use statement

lib/Net/SAML2/SP.pm, t/02-create-sp.t
=> Allow error URI to be a full fledged URI

lib/Net/SAML2/Util.pm
=> Change from 16 to 32 bytes of randomness

lib/Net/SAML2/SP.pm, t/02-create-sp.t
=> Introduce URN_XXX constants in NET::SAML2::SP

lib/Net/SAML2/SP.pm
This cert is only required for the soap_binding function, as it is required in
Net::SAML2::Binding::SOAP. It is also used by post_binding, but there it isn't
required.
=> Make cacert optional in Net::SAML2::SP

lib/Net/SAML2/Protocol/Assertion.pm, t/03-assertions.t, t/12-full-client.t
=> Add nameid as a node so we can get the value and/or the format

lib/Net/SAML2/Protocol/AuthnRequest.pm, lib/Net/SAML2/SP.pm, lib/Net/SAML2/XML/Sig.pm
These commits are lying in my devel branch and have no clear feature/bugfix. Should be non-impacting.
=> Small refactors

lib/Net/SAML2/Binding/SOAP.pm
Enclose the SOAP action in double quotes as described in
https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383528.
Some code code cleanup and improving error messages when request isn't
successful.
=> Refactor Binding::SOAP::request

.github/workflows/linux.yml, Makefile.PL, README, lib/Net/SAML2.pm
=> Bump version string post .57 release

Changes
=> Update Changes for .58 release

lib/Net/SAML2/Binding/Redirect.pm, lib/Net/SAML2/SP.pm, t/06-redirect-binding.t
=> Add support to SP for SSO redirect binding without signed auth request

Makefile.PL, README, lib/Net/SAML2.pm, lib/Net/SAML2/Binding/Redirect.pm, lib/Net/SAML2/Protocol/AuthnRequest.pm, lib/Net/SAML2/SP.pm, t/09-authn-request.t, t/lib/Test/Net/SAML2/Util.pm, xt/testapp/config.yml, xt/testapp/lib/Saml2Test.pm
Also fixes up some post 0.61 issues with the testapp
=> Support ForceAuth and IsPassive for AuthnRequest

xt/testapp/lib/Saml2Test.pm
artifact_request destination should be IdP specified
provide encryption key to decrypt assertion
=> testapp Fix issue in metadata generation missing fully qualified URI

lib/Net/SAML2/Protocol/Assertion.pm, t/03-assertions.t, t/data/eherkenning-assertion.xml
We got the dates from ANY saml:Conditions attribute where we want the condition of the //samlp:Response/saml:Assertion/saml:Conditions xpath.
Added the assertion from the Dutch eHerkenning to prove the failure and subsequent pass of the test
=> Get the correct dates from the assertions

lib/Net/SAML2/Protocol/Assertion.pm, t/03-assertions.t, t/data/saml-adfs-plain.xml
=> Allow assertion without a NameID

lib/Net/SAML2/Protocol/Assertion.pm, t/03-assertions.t, t/05-soap-binding.t
Appears that only the assertion was missing the id
=> Fixes #152 - Incorrect id set on messages from XML

t/author/01-confirm-schema.t, t/data/saml-schema-assertion-2.0.xsd, t/data/saml-schema-protocol-2.0.xsd
Depends on #160 simply adds an author test to ensure that the XML matches the schema
=> Author tests to ensure XML messages comply with schema

Makefile.PL, README, lib/Net/SAML2/SP.pm, t/02-create-sp.t, t/lib/Test/Net/SAML2/Util.pm
Closes: https://github.com/perl-net-saml2/perl-Net-SAML2/issues/165
=> Configure SP without Single Logout Service 

lib/Net/SAML2/SP.pm, t/02-create-sp.t
This allows callers to use it for when you need to find bit in assertions among things
=> Add key_name function to SP

lib/Net/SAML2/Binding/POST.pm
=> Update pod for Net::SAML2::Binding::POST::handle_response

lib/Net/SAML2/Binding/Redirect.pm
=> Update pod for Net::SAML2::Binding::Redirect::verify

lib/Net/SAML2/SP.pm, t/02-create-sp.t
Some IdP's (KPN telecom, NL) don't follow the XML standards for boolean values as defined in https://www.w3.org/TR/xmlschema-2/#boolean
They are reluctant to change their world view as they hold dominance in their markets.
=> Fix boolean values for integrations with crappy IdP's

.github/workflows/shared-workflow.yml
=> Module::Pluggable - don't test
